site_name: JupyterHub-Deployment-ENGR114-2019Q4

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'build'

# Markdown Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc
  - pymdownx.smartsymbols
repo_url: https://github.com/ProfessorKazarinoff/jupyterhub-ENGR114-2019Q4
extra_css: 
    - static/css/toc.css
copyright: 'Copyright &copy; 2018 Peter D. Kazarinoff'

nav:
  - Home: index.md
  - Set Up and Tools: setup.md
  - SSH Keys: ssh_keys.md
  - Server Setup: doserver.md
  - Install JupyterHub: install_jupyterhub.md
  - DNS Routing: DNS.md
  - SSL Certificates: ssl.md
  - Cookie Secret and Proxy Auth Token: cookie_secret_proxy_auth_token.md
  - Install Nginx: nginx_install.md
  - Nginx Configuration: nginx_config.md
  - JupyterHub Configuration: jupyterhub_config.md
  - System Service: systemd.md
  - Google OAuth: google_oauth.md
  - Custom Login Page: login_page.md
  - Cull Idle Servers: cull_idle_servers.md
  - Periodic Maintenance: periodic_maintenance.md
  - Renew SSL Certificate: renew_ssl_cert.md
  - Optional Extras:
      - JupyterLab Default Interface: jupyterlab_default.md
      - Draw.IO extension: draw_dot_IO_extension.md
      - GitHub Extension for JupyterLab: github_extension.md
      - nbGitpuller Plugin: nbgitpuller_plugin.md
      - Defaut URL for nbGitpuller: nbgitpuller_defaut_url.md
      - GitHub Authentication: github_oauth.md
      - Building the Docs: building_docs.md
  - Useful Commands: useful_commands.md
